version: "3"
services:
  varnish:
    image: varnish:latest
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    ports:
      - "2020:80"
    links:
      - nginx
  nginx:
    image: nginx:alpine
    volumes:
      - ./image-proxy:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  php:
    image: php:7.4-fpm-alpine
    volumes:
      - ./image-proxy:/etc/nginx/html/
  imaginary:
    image: h2non/imaginary:latest
    environment:
      PORT: 9000
    command: -enable-url-source
    expose:
      - "9000"
