version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./image-proxy:/etc/nginx/html/
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/30-envsubst-on-nginx.sh:/docker-entrypoint.d/30-envsubst-on-nginx.sh
    ports:
      - "2020:80"
    environment:
      - CACHE_MAX_SIZE=100g
      - CACHE_TTL=1y
      - CACHE_INDEX_SIZE=100m

  php:
    image: php:7.4-fpm-alpine
    volumes:
      - ./image-proxy:/etc/nginx/html/

  imaginary:
    image: h2non/imaginary:latest
    environment:
      PORT: 9000
    command: -enable-url-source -http-cache-ttl 0
    expose:
      - "9000"
