version: "3"
services:
  nginx:
    image: openresty/openresty:centos
    volumes:
      - ./image-proxy:/etc/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/remove-cache-by-key.lua:/bin/remove-cache-by-key.lua
      - ./nginx/remove-cache-by-key.sh:/bin/remove-cache-by-key.sh
    ports:
      - "2020:80"

  php:
    image: php:7.4-fpm-alpine
    volumes:
      - ./image-proxy:/etc/nginx/html/

  imaginary:
    image: h2non/imaginary:latest
    environment:
      PORT: 9000
    command: -enable-url-source -http-cache-ttl 0
    expose:
      - "9000"
