version: "3"
services:
  express:
    build: ./express
    ports:
      - "2020:4000"
    environment:
      - THUMBNAIL_WIDTH=400
      - RENDER_TIMEOUT=10000
      - REACHABLE_TIMEOUT=5000

  imaginary:
    image: h2non/imaginary:latest
    environment:
      PORT: 9000
    command: -enable-url-source -http-cache-ttl 0
    expose:
      - "9000"
